### PR TITLE
fix _amount_ parsing

### PR DESCRIPTION
**Pull request by allowq**
These fixes would be work great with IBKR tax report.

### CODE REVIEW

**Comment by airens** [comment]
> Traceback (most recent call last):
      cashflow.amount = pd.to_numeric([am_str.strip(';') for am_str in cashflow.amount], downcast='float')
      AttributeError: 'float' object has no attribute 'strip'

**Comment by Allowq** [comment]
Looks like "inappropriate python version". You should define appropriate python release on your project. This commit works on Python_3.8.3. I can fix _AttributeError_, but I'm not sure that it is good idea in this situation. You could reject from my MR.
